# Generated by Django 3.0 on 2023-08-03 16:31

from django.db import migrations

def copy_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Profile')
    NewAddress = apps.get_model('profiles', 'Profile')
    for old_obj in OldAddress.objects.all():
        NewAddress.objects.create(
            user=old_obj.user,
            favorite_city=old_obj.favorite_city,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
