version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Run flake8 for PEP8 compliance
          command: flake8
      - run:
          name: Run Tests for all modules
          command: pytest profiles/tests_profiles lettings/tests_lettings --cov=profiles --cov=lettings --cov-fail-under=80
          
      - run:
          name: Login to ECR
          command: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 867318070779.dkr.ecr.us-east-1.amazonaws.com/ecrlettings
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
              docker build \
                --build-arg SECRET_KEY=$SECRET_KEY \
                --build-arg SENTRY_DSN=$SENTRY_DSN \
                --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
                --build-arg DJANGO_DEBUG=$DJANGO_DEBUG \
                -t 867318070779.dkr.ecr.us-east-1.amazonaws.com/ecrlettings:$CIRCLE_SHA1 .
      - run:
          name: Tag Docker image as latest
          command: docker tag 867318070779.dkr.ecr.us-east-1.amazonaws.com/ecrlettings:$CIRCLE_SHA1 867318070779.dkr.ecr.us-east-1.amazonaws.com/ecrlettings:latest

      - run:
          name: Push Docker image with specific tag to ECR
          command: docker push 867318070779.dkr.ecr.us-east-1.amazonaws.com/ecrlettings:$CIRCLE_SHA1

      - run:
          name: Push Docker image with latest tag to ECR
          command: docker push 867318070779.dkr.ecr.us-east-1.amazonaws.com/ecrlettings:latest

      - run:
          name: Configure AWS
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_REGION
      - run:
          name: Sync static files to S3
          command: aws s3 sync static/ s3://oclettingsbucket/
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            aws elasticbeanstalk create-application-version --application-name $APP_AWS --version-label $CIRCLE_SHA1 --source-bundle S3Bucket=$S3_BUCKET_DOCKRUN,S3Key=$DOCKERRUN
            aws elasticbeanstalk update-environment --environment-name $APP_ENVIRONNEMENT_AWS --version-label $CIRCLE_SHA1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
