version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Run flake8 for PEP8 compliance
          command: flake8
      - run:
          name: Run Tests for all modules
          command: pytest profiles/tests_profiles lettings/tests_lettings --cov=profiles --cov=lettings --cov-fail-under=80
      - run:
          name: Login to ECR
          command: $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t 867318070779.dkr.ecr.eu-north-1.amazonaws.com/oc_lettings_site .
      - run:
          name: Push Docker image to ECR
          command: docker push 867318070779.dkr.ecr.eu-north-1.amazonaws.com/oc_lettings_site
      - run:
          name: Sync static files to S3
          command: aws s3 sync static/ s3://oclettingsbucket/

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
